# Generated by Django 3.2.12 on 2023-10-06 09:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AUCTIONS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_start_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('auction_end_date', models.DateField()),
                ('min_bid_amount', models.IntegerField()),
                ('auction_winner', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CATEGORY',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PRODUCTS',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('product_description', models.TextField(max_length=250)),
                ('product_image', models.ImageField(upload_to='images/')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('product_category', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.category')),
                ('product_owner', models.ForeignKey(db_column='product owner', default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BIDS',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('bid_amount', models.CharField(max_length=20)),
                ('auction_id', models.ForeignKey(db_column='auction', default=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.auctions')),
                ('bider_id', models.ForeignKey(db_column='bider', default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product_id', models.ForeignKey(db_column='product', default=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.products')),
            ],
        ),
        migrations.AddField(
            model_name='auctions',
            name='product_id',
            field=models.ForeignKey(db_column='product', default=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.products'),
        ),
    ]
