# Generated by Django 3.1 on 2021-09-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BIDS',
            fields=[
                ('Serial', models.AutoField(primary_key=True, serialize=False)),
                ('pid', models.CharField(max_length=50)),
                ('p_name', models.CharField(max_length=50)),
                ('bider', models.EmailField(max_length=50)),
                ('price', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CUSTOMER',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PRODUCTS',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=50)),
                ('p_des', models.TextField(max_length=250)),
                ('p_photo', models.ImageField(upload_to='images/')),
                ('endate', models.DateField()),
                ('min_bid', models.CharField(max_length=20)),
                ('owner', models.EmailField(max_length=50)),
                ('winner', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
