# Generated by Django 3.1 on 2021-09-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0002_customer_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
