# Generated by Django 3.1 on 2021-10-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0004_auto_20211002_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='owner',
            field=models.EmailField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
