# Generated by Django 4.0 on 2022-01-26 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ebay', '0005_products_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='CUSTOMER',
        ),
        migrations.RenameField(
            model_name='bids',
            old_name='Serial',
            new_name='serial',
        ),
        migrations.AlterField(
            model_name='bids',
            name='bider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='products',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
