# Generated by Django 4.0 on 2022-01-26 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0006_delete_admin_delete_customer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BIDS',
        ),
    ]
