# Generated by Django 4.0 on 2022-01-26 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ebay', '0007_delete_bids'),
    ]

    operations = [
        migrations.CreateModel(
            name='BIDS',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.CharField(max_length=20)),
                ('bider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebay.products')),
            ],
        ),
    ]
