# Generated by Django 4.0 on 2022-01-26 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ebay', '0009_rename_pid_bids_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='bider',
            field=models.ForeignKey(db_column='bider', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='bids',
            name='product',
            field=models.ForeignKey(db_column='product', on_delete=django.db.models.deletion.CASCADE, to='ebay.products'),
        ),
        migrations.AlterField(
            model_name='products',
            name='owner',
            field=models.ForeignKey(db_column='owner', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
