# Generated by Django 4.0 on 2022-02-03 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ebay', '0011_products_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='bids',
            name='bider',
            field=models.ForeignKey(db_column='bider', default=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='bids',
            name='product',
            field=models.ForeignKey(db_column='product', default=True, on_delete=django.db.models.deletion.CASCADE, to='ebay.products'),
        ),
        migrations.AlterField(
            model_name='products',
            name='owner',
            field=models.ForeignKey(db_column='owner', default=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
