# Generated by Django 3.2.12 on 2022-03-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0013_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='min_bid',
            field=models.IntegerField(),
        ),
    ]
