# Generated by Django 3.2.12 on 2023-10-09 15:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auctions', '0006_auto_20231009_2147'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PRODUCTS',
            new_name='PRODUCT',
        ),
    ]
